apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-app.fullname" . }}-secrets
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwtSigningKey: {{ .Values.secrets.jwtSigningKey | default "CHANGE_ME_VIA_SEALED_SECRET" | quote }}
  postgresPassword: {{ .Values.secrets.postgresPassword | default "CHANGE_ME_VIA_SEALED_SECRET" | quote }}
