apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-app.fullname" . }}-web
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "platform-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-app.fullname" . }}-web
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - port: 80
      targetPort: {{ .Values.web.containerPort }}
