-- =============================================================================
-- PlatformApp PostgreSQL 16 Schema — v2
-- Generated by M6 Forward Engineering Agent
-- Rules: UUID primary keys · audit columns (created_at / updated_at) ·
--        FK constraints · unique constraints · indexes per bounded context
-- =============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";    -- trigram indexes for search

-- =============================================================================
-- SCHEMA: catalog
-- Owner: Catalog bounded context
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE catalog.catalog_brands (
    brand_id    UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT  uq_catalog_brands_name UNIQUE (name)
);

CREATE TABLE catalog.catalog_types (
    type_id     UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT  uq_catalog_types_name UNIQUE (name)
);

CREATE TABLE catalog.catalog_items (
    item_id          UUID           NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name             VARCHAR(200)   NOT NULL,
    description      TEXT           NOT NULL,
    price            NUMERIC(18,2)  NOT NULL CHECK (price > 0),
    picture_uri      VARCHAR(500),
    catalog_brand_id UUID           NOT NULL REFERENCES catalog.catalog_brands(brand_id),
    catalog_type_id  UUID           NOT NULL REFERENCES catalog.catalog_types(type_id),
    available_stock  INT            NOT NULL DEFAULT 0 CHECK (available_stock >= 0),
    restock_threshold INT           NOT NULL DEFAULT 0,
    max_stock_threshold INT         NOT NULL DEFAULT 100,
    on_reorder       BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_catalog_items_brand ON catalog.catalog_items (catalog_brand_id);
CREATE INDEX idx_catalog_items_type  ON catalog.catalog_items (catalog_type_id);
CREATE INDEX idx_catalog_items_name_trgm ON catalog.catalog_items USING GIN (name gin_trgm_ops);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION catalog.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_catalog_items_updated_at
    BEFORE UPDATE ON catalog.catalog_items
    FOR EACH ROW EXECUTE FUNCTION catalog.set_updated_at();

CREATE TRIGGER trg_catalog_brands_updated_at
    BEFORE UPDATE ON catalog.catalog_brands
    FOR EACH ROW EXECUTE FUNCTION catalog.set_updated_at();

CREATE TRIGGER trg_catalog_types_updated_at
    BEFORE UPDATE ON catalog.catalog_types
    FOR EACH ROW EXECUTE FUNCTION catalog.set_updated_at();

-- =============================================================================
-- SCHEMA: identity
-- Owner: Identity bounded context
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS identity;

CREATE TABLE identity.user_profiles (
    user_id          UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    username         VARCHAR(200) NOT NULL,
    email            VARCHAR(320) NOT NULL,
    password_hash    VARCHAR(512) NOT NULL,
    role             VARCHAR(50)  NOT NULL DEFAULT 'User' CHECK (role IN ('User','Admin')),
    email_confirmed  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_locked_out    BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_login_count INT        NOT NULL DEFAULT 0,
    last_login_at    TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_profiles_username UNIQUE (username),
    CONSTRAINT uq_user_profiles_email    UNIQUE (email)
);

CREATE TABLE identity.refresh_tokens (
    token_id    UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id     UUID         NOT NULL REFERENCES identity.user_profiles(user_id) ON DELETE CASCADE,
    token       VARCHAR(512) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token)
);

CREATE INDEX idx_refresh_tokens_user ON identity.refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_token ON identity.refresh_tokens (token) WHERE revoked_at IS NULL;

CREATE OR REPLACE FUNCTION identity.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_user_profiles_updated_at
    BEFORE UPDATE ON identity.user_profiles
    FOR EACH ROW EXECUTE FUNCTION identity.set_updated_at();

-- =============================================================================
-- SCHEMA: basket
-- Owner: Basket bounded context
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS basket;

CREATE TABLE basket.baskets (
    basket_id   UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    buyer_id    UUID        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_baskets_buyer UNIQUE (buyer_id)
);

CREATE TABLE basket.basket_items (
    item_id          UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    basket_id        UUID          NOT NULL REFERENCES basket.baskets(basket_id) ON DELETE CASCADE,
    catalog_item_id  UUID          NOT NULL,
    product_name     VARCHAR(200)  NOT NULL,
    unit_price       NUMERIC(18,2) NOT NULL CHECK (unit_price >= 0),
    old_unit_price   NUMERIC(18,2) NOT NULL DEFAULT 0,
    quantity         INT           NOT NULL CHECK (quantity > 0),
    picture_url      VARCHAR(500),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_basket_item UNIQUE (basket_id, catalog_item_id)
);

CREATE INDEX idx_basket_items_basket ON basket.basket_items (basket_id);

CREATE OR REPLACE FUNCTION basket.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_baskets_updated_at
    BEFORE UPDATE ON basket.baskets
    FOR EACH ROW EXECUTE FUNCTION basket.set_updated_at();

CREATE TRIGGER trg_basket_items_updated_at
    BEFORE UPDATE ON basket.basket_items
    FOR EACH ROW EXECUTE FUNCTION basket.set_updated_at();

-- =============================================================================
-- SCHEMA: orders
-- Owner: Orders bounded context
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS orders;

CREATE TABLE orders.orders (
    order_id          UUID           NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    buyer_id          UUID           NOT NULL,
    buyer_email       VARCHAR(320)   NOT NULL,
    order_date        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    ship_to_address   VARCHAR(300)   NOT NULL,
    city              VARCHAR(100)   NOT NULL,
    state             VARCHAR(100)   NOT NULL,
    zip_code          VARCHAR(20)    NOT NULL,
    country           VARCHAR(100)   NOT NULL,
    status            VARCHAR(50)    NOT NULL DEFAULT 'Pending'
                      CHECK (status IN ('Pending','Confirmed','Shipped','Delivered','Cancelled')),
    payment_status    VARCHAR(50)    NOT NULL DEFAULT 'Pending'
                      CHECK (payment_status IN ('Pending','Authorized','Paid','Failed','Refunded')),
    total_amount      NUMERIC(18,2)  NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE TABLE orders.order_items (
    item_id           UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id          UUID          NOT NULL REFERENCES orders.orders(order_id) ON DELETE CASCADE,
    catalog_item_id   UUID          NOT NULL,
    product_name      VARCHAR(200)  NOT NULL,
    unit_price        NUMERIC(18,2) NOT NULL CHECK (unit_price >= 0),
    discount          NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    quantity          INT           NOT NULL CHECK (quantity > 0),
    picture_url       VARCHAR(500),
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_buyer    ON orders.orders (buyer_id);
CREATE INDEX idx_orders_status   ON orders.orders (status);
CREATE INDEX idx_order_items_order ON orders.order_items (order_id);

CREATE OR REPLACE FUNCTION orders.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders.orders
    FOR EACH ROW EXECUTE FUNCTION orders.set_updated_at();

-- =============================================================================
-- SCHEMA: loyalty
-- Owner: Loyalty bounded context (new capability — not in legacy)
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS loyalty;

CREATE TABLE loyalty.membership_tiers (
    tier_id       UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    min_points    INT          NOT NULL CHECK (min_points >= 0),
    multiplier    NUMERIC(5,2) NOT NULL DEFAULT 1.0 CHECK (multiplier > 0),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_membership_tiers_name UNIQUE (name)
);

CREATE TABLE loyalty.loyalty_accounts (
    account_id      UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id         UUID        NOT NULL,
    points_balance  INT         NOT NULL DEFAULT 0 CHECK (points_balance >= 0),
    lifetime_points INT         NOT NULL DEFAULT 0 CHECK (lifetime_points >= 0),
    tier_id         UUID        REFERENCES loyalty.membership_tiers(tier_id),
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_loyalty_accounts_user UNIQUE (user_id)
);

CREATE TABLE loyalty.loyalty_transactions (
    transaction_id   UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    account_id       UUID          NOT NULL REFERENCES loyalty.loyalty_accounts(account_id),
    points_delta     INT           NOT NULL,
    transaction_type VARCHAR(50)   NOT NULL CHECK (transaction_type IN ('Earn','Redeem','Expire','Adjust')),
    source_event_id  VARCHAR(200),
    notes            TEXT,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_loyalty_transactions_event UNIQUE (source_event_id)
);

CREATE TABLE loyalty.reward_rules (
    rule_id      UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name         VARCHAR(200)  NOT NULL,
    points_per_dollar NUMERIC(10,4) NOT NULL DEFAULT 1.0 CHECK (points_per_dollar > 0),
    min_order_amount  NUMERIC(18,2) NOT NULL DEFAULT 0,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    valid_from    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    valid_to      TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_loyalty_accounts_user  ON loyalty.loyalty_accounts (user_id);
CREATE INDEX idx_loyalty_txn_account    ON loyalty.loyalty_transactions (account_id);
CREATE INDEX idx_loyalty_txn_event      ON loyalty.loyalty_transactions (source_event_id) WHERE source_event_id IS NOT NULL;

CREATE OR REPLACE FUNCTION loyalty.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_loyalty_accounts_updated_at
    BEFORE UPDATE ON loyalty.loyalty_accounts
    FOR EACH ROW EXECUTE FUNCTION loyalty.set_updated_at();

CREATE TRIGGER trg_loyalty_tiers_updated_at
    BEFORE UPDATE ON loyalty.membership_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty.set_updated_at();

-- =============================================================================
-- SEED DATA
-- =============================================================================

INSERT INTO catalog.catalog_brands (name) VALUES
    ('Azure'), ('NET'), ('Visual Studio'), ('.NET Foundation'), ('Roslyn')
ON CONFLICT (name) DO NOTHING;

INSERT INTO catalog.catalog_types (name) VALUES
    ('Mug'), ('T-Shirt'), ('Sheet'), ('USB Memory Stick')
ON CONFLICT (name) DO NOTHING;

INSERT INTO loyalty.membership_tiers (name, min_points, multiplier) VALUES
    ('Bronze',   0,    1.0),
    ('Silver',   500,  1.25),
    ('Gold',     2000, 1.50),
    ('Platinum', 5000, 2.00)
ON CONFLICT (name) DO NOTHING;

INSERT INTO loyalty.reward_rules (name, points_per_dollar, min_order_amount, is_active) VALUES
    ('Standard Earn', 1.0, 0.00, TRUE),
    ('Double Points Weekend', 2.0, 25.00, FALSE)
ON CONFLICT DO NOTHING;

-- =============================================================================
-- MIGRATION NOTES
-- =============================================================================
-- To migrate from legacy SQL Server:
--   1. Export SQL Server tables with bcp or SSMS Export Wizard.
--   2. Transform: INT identity PK → UUID (gen_random_uuid()).
--   3. Import using COPY or pg_restore.
--   4. Validate: SELECT COUNT(*) from each table matches source.
--   5. Run application smoke tests before cutting over.
